services:
  contacts-api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ContactsDb=Host=db;Database=contacts-api-db;Port=5432;Username=postgres;Password=1234
    networks:
      - app-network

  db:
    image: postgres:17.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=contacts-api-db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./Dumps/:/docker-entrypoint-initdb.d/
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data: